export const TARGETS = new Set(['detect', 'claude', 'codex', 'both', 'speckit']);

export const DEFAULT_IGNORE_DIRS = new Set([
  '.git',
  'node_modules',
  'dist',
  'build',
  'target',
  'coverage',
  '.next',
  '.nuxt',
  '.cache',
  '.parcel-cache',
  'vendor',
  'tmp',
  'logs',
  '__pycache__',
  '.venv',
  'venv'
]);

export const AI_WORKFLOW_MARKERS = {
  claude: [
    'CLAUDE.md',
    'CLAUDE.local.md',
    '.claude',
    '.claude/CLAUDE.md',
    '.claude/settings.json',
    '.claude/settings.local.json',
    '.claude/commands',
    '.claude/skills',
    '.claude/rules',
    '.claude/agents',
    '.claude/output-styles'
  ],
  codex: [
    'AGENTS.md',
    'AGENTS.override.md',
    '.codex',
    '.codex/config.toml',
    '.codex/rules',
    '.agents',
    '.agents/skills'
  ],
  speckit: [
    '.specify',
    '.specify/memory/constitution.md',
    '.specify/templates',
    'specs'
  ],
  cursor: ['.cursor', '.cursorrules'],
  windsurf: ['.windsurf', 'windsurf.rules'],
  copilot: ['.github/copilot-instructions.md']
};

export const GENERATED_BY = 'Generated by vibe-coding-guardrails';
