import fs from 'node:fs';
import path from 'node:path';
import { writeDefaultConfig, DEFAULT_CONFIG } from './policy.mjs';
import { writeJson, writeText, ensureDir, exists, nowIso } from './utils.mjs';
import { createGateArtifactTemplate } from './gate-artifacts.mjs';

export function initProject({ repo = process.cwd(), target = 'detect', force = false } = {}) {
  const created = [];
  const drafts = [];
  const configFile = writeDefaultConfig(repo);
  created.push(path.relative(repo, configFile));

  for (const dir of ['.guardrails/gates', '.guardrails/approvals', '.guardrails/baselines', 'docs/gates']) {
    ensureDir(path.join(repo, dir)); created.push(`${dir}/`);
  }

  const baseline = {
    generatedAt: nowIso(),
    target,
    note: 'Generated by Vibe Coding Guardrails v2. Review before enforcing in strict mode.',
    config: DEFAULT_CONFIG
  };
  writeJson(path.join(repo, '.guardrails/baselines/project-scan.json'), baseline);
  created.push('.guardrails/baselines/project-scan.json');

  const gateTemplate = createGateArtifactTemplate({ id: 'example-change', riskLevel: 'L2' });
  writeJson(path.join(repo, '.guardrails/gates/example-change.json'), gateTemplate);
  created.push('.guardrails/gates/example-change.json');

  const prTemplate = `# Summary\n\n## Risk Level\n\n- [ ] L0\n- [ ] L1\n- [ ] L2\n- [ ] L3\n\n## Gates\n\n- [ ] Requirement\n- [ ] Design\n- [ ] Test\n- [ ] Security\n- [ ] Release / Rollback\n\n## Gate Artifact\n\nPath: \`.guardrails/gates/<change-id>.json\`\n\n## Tests\n\n## Docs Impact\n\n## Unknowns\n`;
  const draftDir = path.join(repo, '_drafts');
  ensureDir(draftDir);
  writeText(path.join(draftDir, 'PULL_REQUEST_TEMPLATE.vibe-guardrails.draft.md'), prTemplate);
  drafts.push('_drafts/PULL_REQUEST_TEMPLATE.vibe-guardrails.draft.md');

  return { created, drafts };
}
